/**
 * Positions shared between lessons and puzzles, as move lists from an empty
 * board. Columns are 0-based here; the prose in the lessons numbers them 1–7
 * left to right, and rows 1–6 from the bottom, as Allis does.
 *
 * The endgames were generated by a search for a legal move order that reaches
 * a board with exactly the threats the lesson wants and no others, and each
 * one's verdict was then proved by exhaustive search. `tests/content.test.ts`
 * re-proves them on every run.
 */

/** Three stacked in the centre, first player to move. The first ever puzzle. */
export const VERTICAL_WIN = [3, 0, 3, 1, 3, 2];

/** Both sides have three across on the bottom row; first player to move. */
export const HORIZONTAL_RACE = [0, 6, 1, 5, 2, 4];

/** First player has three on a rising diagonal; column 4 completes it. */
export const DIAGONAL_WIN = [0, 1, 1, 2, 3, 2, 2, 3, 3, 6];

/** Second player has three across on the bottom row; first player must block. */
export const BLOCK_THE_ROW = [6, 0, 6, 1, 5, 2];

/** Second player's three on row 2 is not playable yet: the square under it is poison. */
export const FLOATING_THREAT = [0, 1, 2, 0, 6, 1, 6, 2];

/** First player can win in column 5 while the second threatens column 4. */
export const WIN_BEFORE_BLOCK = [4, 0, 4, 1, 4, 2];

/** Same shape without the stack: first player has no win and must block. */
export const JUST_BLOCK = [4, 0, 4, 1, 6, 2];

/** Second player's diagonal threat lands on column 5, row 4. */
export const HIDDEN_DIAGONAL = [3, 1, 4, 2, 3, 2, 0, 4, 4, 3];

/** An open-ended three on the bottom row: two winning squares. */
export const OPEN_THREE = [1, 6, 2, 6, 3];

/** First player can make an open-ended three with either column 2 or column 5. */
export const MAKE_OPEN_THREE = [2, 6, 3, 6];

/** A horizontal and a diagonal that cross: column 4 makes two threats at once. */
export const CROSSING_LINES = [3, 1, 4, 2, 2, 6, 1, 1, 2, 6];

/** One move from a 7 trap: column 5 completes the bar and the diagonal. */
export const SEVEN_BEFORE = [2, 3, 3, 2, 2, 4, 5, 4, 3, 5];

/** The finished 7: threats on column 6 row 3 and column 6 row 4, stacked. */
export const SEVEN_AFTER = [...SEVEN_BEFORE, 4];

/** The same trap a move earlier, second player to move: it can still be broken. */
export const SEVEN_DEFENCE = [...SEVEN_BEFORE, 6];

/** Column 4 forces a block on column 5, which makes column 5 row 2 playable — and winning. */
export const FORCING_ONE = [1, 5, 5, 6, 5, 6, 2, 6, 6, 0];

/** Two independent forcing moves; either order wins in three. */
export const FORCING_TWO = [1, 6, 6, 5, 6, 5, 5, 0, 2, 2];

// --- Endgames (10 or 12 empty squares) --------------------------------------

/** First player has an odd threat (column 1, row 3) and nothing else is on the board. Wins. */
export const ODD_THREAT_X = [
  2, 3, 2, 3, 3, 1, 3, 1, 3, 3, 2, 2, 4, 2, 2, 6, 4, 4, 1, 4, 1, 4, 4, 1, 5, 5, 5, 1, 5, 5, 0, 5,
];

/** Second player has an even threat (column 1, row 4). Wins, whatever the first player does. */
export const EVEN_THREAT_O = [
  3, 3, 1, 3, 1, 3, 3, 2, 3, 2, 2, 2, 5, 2, 2, 4, 5, 4, 4, 1, 4, 4, 0, 1, 1, 5, 5, 4, 5, 1, 5, 0,
];

/** First player has an even threat (column 1, row 4). Only a draw: the wrong parity. */
export const EVEN_THREAT_X = [
  3, 3, 3, 1, 3, 1, 3, 3, 2, 2, 4, 2, 2, 2, 4, 1, 4, 4, 4, 5, 4, 5, 1, 1, 1, 5, 5, 5, 5, 0, 0, 2,
];

/** First player odd threat in column 1, second player even threat in column 7. First player wins. */
export const MIXED_THREATS = [
  3, 1, 3, 1, 3, 3, 2, 3, 3, 2, 2, 5, 2, 5, 2, 2, 4, 4, 1, 4, 5, 4, 4, 4, 6, 5, 5, 1, 5, 1, 1, 0,
];

/** Both threats in column 1: first player's on row 3, second player's on row 4. The lower one wins. */
export const SAME_COLUMN_X_LOWER = [
  4, 3, 4, 3, 3, 3, 0, 2, 2, 3, 2, 2, 2, 3, 2, 4, 4, 1, 4, 1, 1, 1, 1, 5, 5, 4, 5, 1, 5, 5, 5, 6,
];

/** Both threats in column 1: second player's on row 2, first player's on row 3. The lower one wins. */
export const SAME_COLUMN_O_LOWER = [
  2, 3, 1, 3, 3, 2, 3, 3, 3, 4, 2, 2, 2, 2, 4, 4, 6, 1, 1, 1, 1, 5, 1, 5, 5, 4, 5, 4, 4, 6, 5, 5,
];

/** Odd threats for both sides in different columns. A draw, and only one move holds it. */
export const BOTH_ODD = [
  2, 3, 3, 2, 3, 1, 3, 3, 2, 3, 4, 2, 2, 5, 2, 5, 4, 4, 1, 4, 1, 4, 4, 1, 1, 1, 5, 5, 5, 5, 6, 0,
];

/** Three open columns: the centre holds three neutral squares, and whoever takes the last one wins. */
export const THREE_COLUMNS = [
  2, 3, 4, 3, 3, 2, 2, 2, 2, 2, 5, 4, 5, 4, 4, 4, 4, 1, 1, 5, 1, 1, 1, 0, 1, 6, 5, 5, 5, 6,
];
